apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  selector: # manage pods matching label "node-app"
    matchLabels:
      app: node-app
  replicas: 2 # deploy 2 identical pods
  template: # define pod template
    metadata: # apply "node-app" label to pod
      labels:
        app: node-app
    spec: # define container config to run in pods
      containers:
        - name: node-app
          image: node-app
          ports:
            - containerPort: 3000
          imagePullPolicy: Never
